/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "templates": {
        "common": {
            "politeness": string;
            "signature": string;
            "questions": string;
            "info": string;
        };
        "email_changed": {
            "subject": string;
            "title": string;
            "body": {
                "text": string;
                "link": {
                    "text": string;
                    "href": string;
                };
            };
        };
        "register_common": {
            "subject": string;
            "title": string;
            "body": {
                "text": string;
            };
        };
        "register_user": {
            "body": {
                "text": string;
                "link": {
                    "text": string;
                    "href": string;
                };
                "remark": string;
            };
        };
        "register_user_by_admin": {
            "body": {
                "text": string;
                "password": string;
            };
        };
    };
    "validations": {
        "array": {
            "invalid": {
                "format": string;
                "duplicate": string;
                "not_empty": string;
            };
        };
        "boolean": {
            "invalid": {
                "format": string;
            };
        };
        "birth_date": {
            "invalid": {
                "outbound": string;
            };
        };
        "date": {
            "invalid": {
                "format": string;
            };
        };
        "email": {
            "invalid": {
                "format": string;
                "blacklisted": string;
                "size": string;
                "used": string;
                "are_used": string;
                "already_verified": string;
            };
            "success": {
                "verified": string;
            };
        };
        "file": {
            "invalid": {
                "not_provided": string;
                "not_found": string;
                "no_mime_type": string;
                "unauthorized_mime_type": string;
                "infected": string;
            };
        };
        "file_visibility_group": {
            "invalid": {
                "not_found": string;
            };
        };
        "gender": {
            "invalid": {
                "format": string;
            };
        };
        "id": {
            "invalid": {
                "format": string;
                "min": string;
            };
        };
        "ids": {
            "invalid": {
                "format": string;
            };
        };
        "image": {
            "invalid": {
                "aspect_ratio": string;
            };
        };
        "logs": {
            "success": {
                "deleted": string;
            };
        };
        "number": {
            "invalid": {
                "format": string;
                "min": string;
            };
        };
        "password": {
            "invalid": {
                "mismatch": string;
                "weak": string;
            };
        };
        "permission": {
            "invalid": {
                "format": string;
                "already_on": string;
            };
            "not_found": string;
        };
        "phone": {
            "invalid": {
                "format": string;
            };
        };
        "promotion": {
            "invalid": {
                "not_found": string;
                "no_logo": string;
            };
            "success": {
                "deleted_logo": string;
            };
        };
        "role": {
            "invalid": {
                "already_exist": string;
                "already_on": string;
            };
            "not_found": string;
        };
        "string": {
            "invalid": {
                "format": string;
                "uppercase": string;
            };
        };
        "token": {
            "invalid": {
                "format": string;
                "expired": string;
                "unknown": string;
            };
        };
        "user": {
            "invalid": {
                "not_in_file_visibility_group": string;
            };
            "success": {
                "registered": string;
                "deleted": string;
                "deleted_picture": string;
                "deleted_banner": string;
            };
            "cannot_update": string;
            "not_found": {
                "email": string;
                "id": string;
            };
            "unverified": string;
            "picture": {
                "cooldown": string;
                "not_found": string;
            };
            "banner": {
                "not_found": string;
            };
        };
        "users": {
            "not_found": {
                "ids": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
