/**
 * Avoid the need to install nestjs-i18n in order to use the types
 * -> as the i18n.d.ts file is generated by the library and use this type
 */
export type Path<T> = keyof T extends string
	? PathImpl2<T> extends infer P
		? P extends string | keyof T
			? P
			: keyof T
		: keyof T
	: never;
